spring:
  application:
    name: picket


#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id:
#            client-secret:
#            client-name: Kakao
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            scope: profile_nickname
#            client-authentication-method: client_secret_post
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

  datasource:

    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.drop-cascade: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  cloud:
    aws:
      credentials:
        access-key: ${access_key}
        secret-key: ${secret_key}
      s3:
        bucket: ${bucket}

      region:
        static: ap-northeast-2

  mail:
    host: smtp.gmail.com
    port: 587
    username: picketnologya@gmail.com
    password: ayxh dkbf tdgm grkj
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  jackson:
    time-zone: Asia/Seoul
    locale: ko_KR

password:
  reset:
    redirect:
      url: ${PWD_RESET_REDIRECT_URL}

redis:
  host: ${REDIS_HOST}
  port: 6379

portone:
  key:
    api-secret: ${PORT_ONE_API_SECRET}
    store-id: ${STORE_ID}
    webhook: ${WEB_HOOK_SECRET}